HeroHQ_Dynamic/Models/Context.cs
using System.Data.Entity;

namespace HeroHQ_Dynamic.Models
{
    // Classe Context
    // Un "contexte" est comme son nom l'indique l'ensemble des
    // éléments utilisé par votre programme pour fonctionner
    // Plus précisément, un contexte en informatique est souvent
    // utilisé pour faire référance à la base de donnée
    public class Context : DbContext
    {
        // DbSet est une collection qui agit comme une basse de donnée et qui
        // est utilisée par EntityFramework
        public DbSet<Hero> Heroes { get; set; }
    }
}

HeroHQ_Dynamic/Models/Hero.cs
using System.ComponentModel.DataAnnotations;

namespace HeroHQ_Dynamic.Models
{
    // Classe "Hero", elle représente notre modèle dans la base de donnée
    public class Hero
    {
        // [Key] est une annotation pour signaler à EntityFramework
        // que le champ Id est une clé primaire
        [Key]
        public int Id { get; set; }
        public string Nom { get; set; }
        public int Age { get; set; }
        public string Pouvoir { get; set; }
        public string Citation { get; set; }
        public string Photo { get; set; }
    }
}

HeroHQ_Dynamic/Controllers/HeroController.cs
using HeroHQ_Dynamic.Models;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace HeroHQ_Dynamic.Controllers
{
    // HeroController gère toutes les pages du site (sauf l'accueil)
    // Ce controller gère l'affichage des héros sur les pages de recherche et
    // en détails, ainsi que la création de ces derniers
    public class HeroController : Controller
    {
        // Lien vers la Base de donnée
        // Ce champs est private, seul le Controller peut y acceder.
        private Context bdd;

        // Lorsque l'on utilise le controller, on charge notre base de données grâce au constructeur.
        public HeroController()
        {
            bdd = new Context();
        }

        // Gère l'affichage d'un héros en détail
        #region Détails
        public ActionResult Details(int id)
        {
            // Si id est négatif, c'est une erreur!
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Récupération des informations du héro avec son Id
            Hero hero = bdd.Heroes.Where(h => h.Id == id).Single();

            // Test pour vérifier que le héro existe
            if (hero == null)
            {
                return HttpNotFound();
            }

            return View(hero);
        }
        #endregion

        // Gère la recherche de héros
        #region Recherche
        [HttpGet]
        public ActionResult Search(string heroName)
        {
            /* Cette requète est à la fois compliquée et très simple.
             *  
             * Il s'agit d'une requète Linq, encapsulée dans une fonction Lambda...
             * 
             * Linq est l'accronyme de "Language Integrated Query" est agit comme du SQL
             * pour manipuler une base de données.
             * 
             * Une fonction Lambda est une fonction anonyme, c'est à dire une fonction sans
             * nom donc l'expression est directement passé entre parenthèses.
             * Par exemple: (h => h.Id >= 3) me renvoie les éléménts "h" ayant un Id supérieur
             * ou égal à 3... 
             * 
             * Cette fonction cherche tout les héros dont le nom en minuscule contient le nom
             * recherché en minuscule puis tri les résultas par ordre alphabétique, et
             * met ces résultats dans une liste.
            */

            
            /*
             * Si il n'y a pas de paramètre passé, on prends "" comme valeur par défaut.
             * "" étant présent dans tout les noms de héros, on obtiendra la liste de tout les héros.
            */ 
            if (heroName == null)
                heroName = "";

            heroName = heroName.ToLower();

            var heroSearch = bdd.Heroes.Where(h => h.Nom.ToLower().Contains(heroName))
                            .OrderBy(h => h.Nom)
                            .ToList();

            if (heroSearch == null)
            {
                return HttpNotFound();
            }
            return View(heroSearch);
        }
        #endregion

        // Gère l'ajout d'un nouveau héros
        #region Nouveau Héros
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Hero/Create
        // HttpPost est utilisé pour envoyer une information au serveur
        [HttpPost]
        public ActionResult Create(string heroName, int heroAge, string heroPow, string heroCit, string heroImg)
        {
            // Création d'un héro. Noter qu'on ne lui affecte pas d'Id!
            // L'Id est crée automatiquement quand on ajout une entrée à la bdd.
            var newHero = new Hero();
            newHero.Age = heroAge;
            newHero.Citation = heroCit;
            newHero.Nom = heroName;
            newHero.Photo = heroImg;
            newHero.Pouvoir = heroPow;

            // On l'ajoute à la base de données.
            bdd.Heroes.Add(newHero);

            try
            {
                // On essaye de sauvegarder!
                bdd.SaveChanges();
            }
            catch (Exception)
            {
                // Si erreur, on retourne sur la page de création du héro.
                return View();
            }

            // Sinon on retourne sur la page du héros créé.
            int heroID = bdd.Heroes.First(h => h.Nom == heroName).Id;
            return Redirect("/Hero/Details/" + heroID);
        }
        #endregion
    }
}

HeroHQ_Dynamic/Controllers/HomeController.cs
using HeroHQ_Dynamic.Models;
using System.Linq;
using System.Web.Mvc;

namespace HeroHQ_Dynamic.Controllers
{
    // HomeController est le controller qui s'occupe de l'accueil
    public class HomeController : Controller
    {
        // Lien vers la Base de donnée
        // Ce champs est private, seul le Controller peut y acceder.
        private Context bdd;

        // Lorsque l'on utilise le controller, on charge notre base de données grâce au constructeur.
        public HomeController()
        {
            bdd = new Context();
        }

        public ActionResult Index()
        {
            /* Les informations que nous voulons afficher à l'accueil est une liste de héros.
             * Pour cela, nous allons récuperer certains héros dans la base de données.
             * Cette requète est à la fois compliquée et très simple.
             *  
             * Il s'agit d'une requète Linq, encapsulée dans une fonction Lambda...
             * 
             * Linq est l'accronyme de "Language Integrated Query" est agit comme du SQL
             * pour manipuler une base de données.
             * 
             * Une fonction Lambda est une fonction anonyme, c'est à dire une fonction sans
             * nom donc l'expression est directement passé entre parenthèses.
             * Par exemple: (h => h.Id >= 3) me renvoie les éléménts "h" ayant un Id supérieur
             * ou égal à 3... 
             * 
             * Cette fonction cherche les héros dont l'age est supérieur à 35,
             * sélectionne les 8 premiers, et met les résultats dans ma liste.
            */
            var herosDispo = bdd.Heroes.Where(h => h.Age > 35)
                               .Take(8)
                               .ToList();

            // Le Controller retourne à la View herosDispo pour qu'elle puisse l'afficher.
            return View(herosDispo);
        }
    }
}

HeroHQ_Dynamic/Views/Hero/create.cshtml
<!-- Ici pas besoin de Model, on n'affiche rien en dynamique -->

<!-- Nouveau Hero -->
<div class="col-xs-12 col-sm-9">
    <div class="content" id="new_hero">
        <h1 class="page-title">Nouvelle candidature</h1>
        <section class="section">

            <!-- Formulaire utilisé pour créer un nouveau héro -->
            @using(Html.BeginForm("Create", "Hero", FormMethod.Post))
            {
                <div class="row">
                    <!-- Colonne de gauche -->
                    <div class="col-xs-6">
                        <p class="line">
                            <label for="">Quel est votre nom de héros ?</label>
                            <input type="text" class="mb0 wide" id="heroName" name="heroName" required>
                        </p>
                        <p class="line">
                            <label for="">Quel âge avez vous ?</label>
                            <input type="number" class="mb0 wide" id="heroAge" name="heroAge" required>
                        </p>
                        <p class="line">
                            <label for="">Quel est votre pouvoir ?</label>
                            <input type="text" class="mb0 wide" id="heroPow" name="heroPow" required>
                        </p>
                        <p class="line">
                            <label for="">Quel est votre citation de référance ?</label>
                            <input type="text" class="mb0 wide" id="heroCit" name="heroCit" required>
                        </p>
                    </div>

                    <!-- Colonne de droite -->
                    <div class="col-xs-6">
                        <p class="line">
                            <label for="">Photo du héros</label>
                            <input type="file" class="mb0" id="heroImg" name="heroImg" required>
                        </p>
                        <p class="line ac">
                            <img class="current_img" src="/images/hero_img_placeholder.png" alt="Visuel hero" width="200" height="200">
                        </p>
                    </div>

                    <!-- Saut de ligne -->
                    <div class="col-xs-12">
                        <div class="hr mt2 mb2"></div>
                    </div>

                    <!-- Boutton pour valider -->
                    <div class="col-xs-12 ac">
                        <button type="submit" class="btn btn_color3 recette_save">
                            <span class="glyphicon glyphicon-ok mr0"></span><span>Valider ma candidature</span>
                        </button>
                    </div>
                </div>
            }

        </section>
    </div>
</div>

HeroHQ_Dynamic/Views/Hero/details.cshtml
@using HeroHQ_Dynamic.Models;

<!-- Model utilisé par la View pour afficher le détail d'un héro -->
@model Hero


<!-- Hero Details -->
<div class="col-xs-12 col-sm-9">
    <div class="content" id="hero_details">
        <h1 class="page-title">Un héros en détail</h1>

        <section class="section details">
            <div class="row">
                <!-- Affichage de l'image à gauche -->
                <div class="col-vxs-12 col-xs-6 col-sm-5">
                    <div class="avatar-wrap">
                        <img class="avatar" src="/images/@Model.Photo" alt="@Model.Nom">
                    </div>
                </div>
                <!-- Affichage des informations à droite -->
                <div class="col-vxs-12 col-xs-6 col-sm-7">
                    <div class="infos">
                        <h1 class="name">@Model.Nom</h1>
                        <p><span><span class="fwb">Citation :</span> @Model.Citation</span></p>
                        <p><span><span class="fwb">Âge :</span> @Model.Age ans</span></p>
                        <p><span><span class="fwb">Pouvoir :</span> @Model.Pouvoir</span></p>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

HeroHQ_Dynamic/Views/Hero/search.cshtml
@using HeroHQ_Dynamic.Models;

<!-- Ici le model utilisé par la View ne sert pas directement à afficher
     des informations, mais est utilisée dans la vue partielle -->
@model List<Hero>

<!-- Search -->
<div class="col-xs-12 col-sm-9">
    <div class="content" id="content_search">
        <h1 class="page-title">Tout les héros</h1>
        <div class="row">
            <div class="col-xs-12">
                <div class="panel">
                    <div class="row imgback">
                        <div class="hidden-xs col-sm-3"></div>
                        <div class="col-xs-12 col-sm-9 fp">
                            <div class="filters">

                                <div class="filters" id="filters">
                                    <!-- Formulaire de recherche -->
                                    @using(Html.BeginForm("Search", "Hero", FormMethod.Get))
                                    {
                                        <div class="filter">
                                            <p><label for="">Nom du héros</label></p>
                                            <p><input type="text" name="heroName" id="heroName" placeholder="ex: Reaper"></p>
                                        </div>
                                        <button type="submit" class="btn btn_big btn_color1" value="Submit" id="SubmitBtn">
                                            Trouver un héros
                                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                        </button>
                                    }
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <!-- Affichage du résultat de la recherche -->
                <div class="result">
                    <div class="heroes row">
                        <div class="col-xs-12">
                            <!-- Si le modèle est null ou vide, la recherche à été infructueuse -->
                            @if (Model == null || Model.Count == 0)
                            {
                                <p class="col-xs-12 blank">Aucun Hero ne correspond à votre recherche</p>
                            }
                            else
                            {
                                <!-- Sinon on affiche le(s) héro(s) grâce à une vue partielle -->
                                foreach (var hero in Model)
                                {
                                    @Html.Partial("_Hero", hero)
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HeroHQ_Dynamic/Views/Home/index.cshtml
@using HeroHQ_Dynamic.Models;

<!-- Ici le model utilisé par la View ne sert pas directement à afficher
     des informations, mais est utilisée dans la vue partielle -->
@model List<Hero>

<!-- Home -->
<div class="col-xs-12 col-sm-9">
    <div class="content" id="content_home">
        <h1 class="page-title">Bienvenue à la base des Héros !</h1>

        <section class="section">
            <h2 class="title">~ Nos héros disponibles ~</h2>
            <div class="heroes row">
                <!-- Affichage de quelques héros disponibles -->
                @foreach (var hero in Model)
                {
                    @Html.Partial("_Hero", hero)
                }
            </div>
        </section>

        <!-- Affichage de la section Nouveau héro -->
        <section class="section newhero">
            <div class="row">
                <div class="col-xs-12">
                    <p class="c">Vous êtes un héros ? Rejoingez nous !</p>
                    <p class="b">
                        <a href="@Url.Action("Create", "Hero")" class="btn btn_color1">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                            <span>Créez un nouveau héros !</span>
                        </a>
                    </p>
                </div>
            </div>
        </section>
    </div>
</div>

HeroHQ_Dynamic/Views/Shared/_Hero.cshtml
@using HeroHQ_Dynamic.Models

<!-- Model utilisé par la View pour afficher le héros -->
@model Hero

<div class="col-xs-6 col-sm-3 hero">
    <a href="/Hero/Details/@Model.Id">
        <img src="/images/@Model.Photo" alt="@Model.Nom" height="175" width="150">
        <div class="bot">
            <p class="name">@Model.Nom</p>
        </div>
    </a>
</div>

HeroHQ_Dynamic/Views/Shared/_Layout.cshtml
<!-- Le layout est le nom de la vue qui englobe toutes les autres -->
<!-- On présise aux navigateur le languague utilisé, ici HTML -->
<!DOCTYPE html>
<html>

<!-- La section "head" contient les informations utilisés par votre navigateur -->
<head>
    <meta charset="utf-8" />
    <title>Heroes H.Q. Néo</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="c17 engineering" />
    <meta name="copyright" content="c17 engineering" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
    <meta name="apple-mobile-web-app-title" content="Hero H.Q. Néo">
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <link rel="shortcut icon" href="~/images/favicon.png" />
    <link rel="image_src" href="~/images/favicon.png" />
    <link rel="icon" type="image/png" href="~/images/favicon.png" />
    <!-- Ici on dit quel scripts utiliser -->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>

<!-- La section "body" contient les informations que l'on doit afficher -->
<body>
    <div id="wrapper">
        <!-- Header -->
        <header id="header">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <a href="@Url.Action("Index", "Home")" class="logo">
                            <img src="/images/herohqbanner.png" alt="" width="350" height="130">
                        </a>
                        <div class="desc">
                            <p>Besoin d'un héros ?<br />Trouvez celui qu'il vous faut!</p>
                            <p><a class="link" href="@Url.Action("Search", "Hero")"><strong>De nombreux héros</strong> à votre service !</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" id="mobile-menu-btn">
                <i class="glyphicon glyphicon-menu-hamburger"></i>
            </button>
        </header>

        <main id="main">
            <div class="container">
                <div class="row">
                    <!-- Barre de navigation -->
                    <div class="col-sm-3" id="col-nav">
                        <button type="button" id="mobile-close-btn">
                            <i class="glyphicon glyphicon-remove"></i>
                        </button>
                        <nav id="nav">
                            <ul class="menu">
                                <li class="page_hom">
                                    <a href="@Url.Action("Index", "Home")">
                                        <span>Accueil</span>
                                    </a>
                                </li>
                                <li class="page_rec">
                                    <a href="@Url.Action("Search", "Hero")">
                                        <span>Recherche</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>

                    <!-- Rendu des vues partielles ici -->
                    @RenderBody()

                </div>
            </div>
        </main>

        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <div class="row footer-hero-wrap">
                    <div class="hidden-xs col-sm-3">
                        <div class="footer-hero"></div>
                    </div>
                    <div class="col-xs-12 col-sm-9">

                        <p>Le QG des héros est situé 8 avenue de la Justice. Tél: 06.65.59.66.30.30 Mail: ausecours@hero.com</p>

                        <a href="@Url.Action("Index", "Home")" class="btn btn_color1">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                            Revenir à l'acceuil
                        </a>

                        <div class="hr"></div>
                        <p class="copyright">Crée pour la Formation Néo. Images tirés d'Overwatch™, un jeu Blizzard Entertainment™.</p>
                        <p class="copyright">Ne pas publiez sans l'accord de l'éditeur.</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>